
#pragma once

/* included again here just
 * so we don't have to provide
 * the OpenAL headers here.     */
typedef enum {
    AUDIO_REVERB_GENERIC,
    AUDIO_REVERB_PADDEDCELL,
    AUDIO_REVERB_ROOM,
    AUDIO_REVERB_BATHROOM,
    AUDIO_REVERB_LIVINGROOM,
    AUDIO_REVERB_STONEROOM,
    AUDIO_REVERB_AUDITORIUM,
    AUDIO_REVERB_CONCERTHALL,
    AUDIO_REVERB_CAVE,
    AUDIO_REVERB_ARENA,
    AUDIO_REVERB_HANGAR,
    AUDIO_REVERB_CARPETEDHALLWAY,
    AUDIO_REVERB_HALLWAY,
    AUDIO_REVERB_STONECORRIDOR,
    AUDIO_REVERB_ALLEY,
    AUDIO_REVERB_FOREST,
    AUDIO_REVERB_CITY,
    AUDIO_REVERB_MOUNTAINS,
    AUDIO_REVERB_QUARRY,
    AUDIO_REVERB_PLAIN,
    AUDIO_REVERB_PARKINGLOT,
    AUDIO_REVERB_SEWERPIPE,
    AUDIO_REVERB_UNDERWATER,
    AUDIO_REVERB_DRUGGED,
    AUDIO_REVERB_DIZZY,
    AUDIO_REVERB_PSYCHOTIC,
    AUDIO_REVERB_CHAPEL
} AudioEffectReverb;

void InitAudio(void);
void ShutdownAudio(void);